### ISSUE TITLE
str_to_seq_aln.py  argument of type 'numpy.int64' is not iterable

### ISSUE THREAD

**Issue by kehan777** [patrickbryant1/binder_design#1]
Making alignment..
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-22-d5fac1cb2774>](https://localhost:8080/#) in <module>
     19   #Create MSA
     20   print('Making alignment..')
---> 21   aln, ids, evals = make_aln(target_seq, OUTDIR+'/str_aln/',eval_threshold)
     22   write_a3m(OUTDIR+'/str_aln/'+PDBID+'_str.a3m', aln, ids, evals)

[/content/binder_design/src/process/str_to_seq_aln.py](https://localhost:8080/#) in make_aln(query_seq, results_dir, eval_t)
     43         for i in range(len(qstart)):
     44             qs_i, qe_i, qaln = qstart[i]-1, qend[i], query_alns[i]
---> 45             if '-' in qaln:
     46                 #Get the insertions and remove them from the hit aln
     47                 insertions = np.argwhere(np.array([x for x in qaln])=='-')[:,0]

TypeError: argument of type 'numpy.int64' is not iterable

**Comment by patrickbryant1** [comment]
Hi, this repo is not live yet. It will be released later this year.
